### ISSUE TITLE
redirect www subdomain to https://simpeg.xyz

### ISSUE THREAD

**Issue by lheagy** [simpeg/website#18]
Right now, https://simpeg.xyz/ doesn't work... we have been redirecting traffic from http://simpeg.xyz to https://www.simpeg.xyz which. However, I think it would be much simpler to go the other way - redirect people who put in `www.simpeg.xyz` to `simpeg.xyz` 

cc @rowanc1 

![image](https://user-images.githubusercontent.com/6361812/41172657-601c1aec-6b09-11e8-8d61-e1118b64fe95.png)

**Comment by rowanc1** [comment]
![image](https://user-images.githubusercontent.com/913249/45258442-b770c780-b374-11e8-8d70-252a40c04d78.png)

Should be fixed. Will take a while to propagate.

**Comment by lheagy** [comment]
Thanks @rowanc1!!
