### ISSUE TITLE
Google App Engine Local

### ISSUE THREAD

**Issue by lheagy** [simpeg/website#2]
I tried launching the site locally through the gae gui, but am running into issues with trying to import markdown

![image](https://cloud.githubusercontent.com/assets/6361812/17560225/1bd390c2-5ed6-11e6-83bd-149a0d6606ac.png)

Any suggestions?

**Comment by rowanc1** [comment]
`make symlinks`

**Comment by rowanc1** [comment]
`make run`

**Comment by rowanc1** [comment]
I usually don't use the gui!

**Comment by bsmithyman** [comment]
@lheagy: Go to the GoogleAppEngineLauncher >> Preferences menu item, and set the Python path to point to the Python 2.7 executable from you Anaconda installation (e.g., `/Users/brendan/anaconda/bin/python2.7`). That should pick up the installed packages properly.

**Comment by lheagy** [comment]
ah, thanks @bsmithyman !
