### ISSUE TITLE
use github pages?

### ISSUE THREAD

**Issue by lheagy** [simpeg/website#22]
- related to #17 

I propose we consider using GitHub pages for the SimPEG website. Currently, we aren't (in practice) maintaining the site, and the pool of contributors is limited to people who are willing to learn html / css. This is a small subset of the SimPEG team. Building a site from a collection of markdown pages or similar would enable a broader group of people to get involved. In my opinion, we should prioritize including more people. 

I realize that this would limit some of the ideas we have listed in #17, but I think it might mean we move forward. This doesn't preclude moving to a new framework (e.g. similar to @rowanc1's personal site) when the tech stabilizes if it is sufficiently easy to contribute to. 

Thoughts?

**Comment by rowanc1** [comment]
Yes, I think that is a good idea to move away from the custom setup that we have at the moment. I keep trying to get this higher up on my priorities, but never quite make it.

Perhaps pulling on some of the ideas in the pelecan side?

**Comment by rowanc1** [comment]
This is now complete!
