### ISSUE TITLE
All journal articles are down

### ISSUE THREAD

**Issue by thast** [simpeg/website#8]
all the journal articles are not accessible anymore (see screenshot).
This problem is not new for some of them but I do remeber accessing the "Frequency Domain Implementation" or the "Primary-Secondary Field Formulation" in September.

![500 internal server error - google chrome 2016-10-26 10 54 03](https://cloud.githubusercontent.com/assets/13682747/19738044/c2f8bf0a-9b6a-11e6-9cfe-b78485486f77.png)

@rowanc1 , @lheagy ?

**Comment by rowanc1** [comment]
Yeah. I gotta fix that. We are over quota on the github API. 

Thanks for pushing on this.

**Comment by rowanc1** [comment]
Should probably use something like this:

https://github.com/getpelican/pelican-themes/tree/master/pelican-bootstrap3

**Comment by rowanc1** [comment]
Yeah. I gotta fix that. We are over quota on the github API.

Thanks for pushing on this.
R
