### ISSUE TITLE
slack link

### ISSUE THREAD

**Issue by lheagy** [simpeg/website#9]
we should add a `connect` panel: slack, email, twitter, youtube, github. 

Maybe along the lines of: http://disc2017.geosci.xyz/ ? 

Thoughts?

![image](https://cloud.githubusercontent.com/assets/6361812/19981984/c2902c0a-a1c9-11e6-869e-5aa00e43c5b6.png)

**Comment by rowanc1** [comment]
I would say we should just migrate the entire website to using the disc like layout. It is much better.

**Comment by rowanc1** [comment]
I think we can have some extra pages etc.

**Comment by rowanc1** [comment]
Complete.
